server:
  port: 5055

spring:
  application:
    name: vector-service


  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: vector-service-group
      auto-offset-reset: latest
      enable-auto-commit: true

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.retail.vector.dto.DocumentEvent

#############################################################
# MinIO
#############################################################
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: documents

#############################################################
# Qdrant
#############################################################
qdrant:
  host: localhost
  port: 6334
  use-tls: false
  collection-name: mapping-documents
  # api-key:
  payload:
    chunk-segment-threshold: 5
    chunk-char-thresholdL: 1800
    

#############################################################
# Ollama
#############################################################
ollama:
  base-url: http://localhost:11434

  embedding:
    model: nomic-embed-text:latest

#############################################################
# AI Service
#############################################################
ai:
  service:
    url: http://localhost:5056

#############################################################
# Kafka Topics
#############################################################
app:
  kafka:
    topic:
      document-events: document-events

#############################################################
# Logging
#############################################################
logging:
  level:
    root: INFO
    com.retail.vector: DEBUG
    org.springframework.kafka: INFO